sudo: false
dist: trusty
language: node_js
node_js:
  - stable
branches:
  except:
    - gh-pages
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
before_script:
  - npm install
  - 'export PATH=$PWD/node_modules/.bin:$PATH'
script: echo "This design module has no tests"
after_success:
  - 'if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$DEPLOYSECRET" -in deploy.enc -out deploy_key -d; fi'
  - cd $TRAVIS_BUILD_DIR/scripts
  - chmod 755 ghp.sh
  - ./ghp.sh
env:
  global:
    - secure: uP2/gEHWCdklvSv5tMURcczm9E9cEhkcF4josxoHhknd6Bn7zQbIwoRrPb2dAySorlc34auFNt5VvugFvqlMEOP38m3vLs7y72A0EPJ7LdRAzGCuf/OWvctGocezT1dqylGdkJgfr488kq/1yA+d4KhOiGDrHB32EWp7dLJ/MF49jrzDpCNd62AESj66rvn1ioDGP5vv7fnyQY5le0SAoswZ4HzvFOwBxQuRMGkH+lh4qXyXNs5Nlje5ZWORVFLKl7MA8wIMS3SBosKVRaUtBQ4gMf+9TGK5bY4EhLGmU41wBmd1WAeWbUlHvvFvc/r1CJN41DRyugxzGqQUTvFwDeZN31oyHqbXpnDdNrnl4GeszSCWNRRCn2RjnRdqE2iW3pjo4OECwpmyha0OTkeevSAn/ROMoUSSwpUM+vbRZDZIfQjs97/TsmyobB7DZ+txpTguLTNzw+N3lMJSlN51gNtTsMBp2RFDmJLjwoy7brKtvqrc4gvyK9YECRA1d6tiDKqxy0oX/E3nL0I5wuoxHt/dCfKd4FMndaT6PefbQVEc4lnUqJhg0BvmO8MHfEPUfZDg2fhIv1+xyh81mX+GKSdFrDe9u1VoP2MmnMHYDBV0We3K9bSqk1uP5RDjCm92rpJds3oo8ZivxJ7FcRkU0fqAgBZvH/Abt7QKmsU1o0k=
    - secure: SmayJPw8pyrM+6uNciDaEn85Ar5Pw7Maeh+3LPi3vLKPJcQU6kQEsJRldYmjJpby+cIqsWxeHHuykRpJ/+IRsMmcNHHqZgT4qTo84kfpG/hggEVrObG4lxsDRmDiu0xVTGtpGkGO1HHMEVcGzkhsu1hWNHr6XxSJPgSXIE9AdQYqd+yHe7/jHi7RJY0wABIWUKR8ZEp64W6Icuzcdxn/7oMvNlu1xlgdPH7FKnqFNnIA4GTF8gpDu8YtpR8pmwxKreXwX+98vTVSto/rU+Wa/nVsHiwpdQqEBI9Ys1JwSeC8RjbB+5C58FT8v1TTgpktvnbYMW7WvjLNiGjEKhPd0OIAui0PrBTO3ewzFCZrwXVFWAwxRNnWDQmgF0fWCjJeGp4/RXFlRIiw9QwSi5jkGJo5zh3XInqoJVqDgnqNuU8+EwE3pos7P4qZwunMXXjW1j9sQI7koO9e+ejR/mfN/ewlpPTW0L2v9YWOeCnPnzEryJn3CIeZ0w97pAjzZzEzrZezXvjeflhat6NM0/4cB72vrItGYt+bdFG9eISW7wOaPTjfQtokztfAL46Gi6vDyVw4XgcnSL7F2y799tDJQwEa5EP9HAt2wxOzZ+EQuheg1TsEY5V7yazF3y50TWYx3GwPwLphTwX3hhT79IA6Mchxd/U2nFhBzh/xImbDxi0=
    - secure: InEm37N9urZTrMMIlPT3H5FmyCW+rXNl8jJedD/lrcoDnrqYSLZCjd0auHn7fSOlCBs6VDNOEl7gf74y+ZPfNfJR5YZW9EGULq6z8dD3mR5puqdE1rSnLuGcnY3kOcW31KadTGznJCnpPlVIQAom0nDZDZL6wu3Zp2li6LcB76rFB28T8NvGRMLBC4UoVHcGPHqJu4/POSJ/WONQuV/T2sz0YxZQEUZSxJ9UCyTRizzgl44xQRz1XUQ/UfFYCajxUDBodfFwZ4MZIOrR8rzhPncSGYXxshpnuIfHLDR5aygDk7F7YKgEMnmn6qNqGCHhkR3aVVodqcXTYZtBDiPRO1ZUcosJ2XbkhXOLzcQTCXdpm3Z+SptxZwa16NqQvSttC4/7G9dm8/3VQeTZZnEOuNXeHQKccH14ei72c1cfT0N+COdNBzB6z15PdXEi4y7j75r2B0Hs/VVvJPDSBb+UIaEBgIm6BjZKFXbeLIWENj+EKGzKOybzBd8WEP/ZdabLd13xk6z2/HVsqERJRqr54en7bLffo9DVIt1svspI8M4l53LqGkQ8+ns4VppEgRu/EoKSrlpRbSrfSMrTcultJpLYuoh3p+6aV0yBw7PWb61hBgLZq6USVNdCberzR7R95JGdYLqFSd/pi8Db7LWa/eo9XZbB6nYi9Vwyt6F4Ibo=
    - secure: Qw6pDEIfhdBjL9JuXy/1OO7z5AHNVpBbraZjBz6G0p3CHmXatzMIuFn80m5MuA96+REUezwCPwfna9WtcXRmFDo4cOZMB1l3bGJVbzIoHWivIIAW2O2OvORRFlzujtG0dsIxHwfcSnXXynyh8S0iTqKXhshgs3YQSOLIRCqnZ+hDxa2q3FBuWxAc06Tx5eVdkUjyOPGNsIDZH6f+D7lZXGJRHnC8g5IbO3xIrFw6lTrglChlIJrSkMK366bKFZTzGqu9GnW9ia6oMuEhys7hXYj6WMMMzARbkaHWscdzFJ9v3vqeeaSptWIo1lK/+vhMbqzMdPqJhig+v1PtmBFi7CBM9IFHNPvAI45bZXYTKneNu1Wew+iAY+/SEJVSpVlchxp5rzzIQrhxukVhtA27lpsGphTzCq1IMjJ4QzoIeJr4r0bz0uCuoiOJn2BCH8wjnrDb6OGDyM5VUiEMKgUk3s83QqSS2z3G+rn9YOIpGJo+Bn+IK/MYuF8bRxvO0beoNpEIhUbrwZEQ35aOEt4xzaHLOBHx6RNevKD2iHlLAeVPOoZHbRrjbqPW/+qFQ91V2dn8nuK+fBHTY56Uj+BAsHjT52X3zivtJWplZC+El74X+GAwCyg4Y7xcQES6bqrwF83FYNUs3W1AyGTrXDXVnQCaq3cTSclaBR3j4YWxIJ0=

