sudo: required
dist: trusty
language: node_js
node_js:
- stable
branches:
  only:
  - master
before_script:
- npm install bower
- export PATH=$PWD/node_modules/.bin:$PATH
- bower install
script:
- cd $TRAVIS_BUILD_DIR/scripts
- chmod 755 ghp.sh
- ./ghp.sh
before_install:
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then openssl aes-256-cbc -k "$password"
  -in id_rsa.enc -out deploy_key -d; fi
env:
  global:
  - secure: Bj6g/GPZsXxneF9AG+B0/s4Oa3M/uO/LoIg3XUkSTizZZstcRU+krgYLGeD4HhYCieensJgS0BJrQydOvmrIH3iqA9LsCyY940LNoLI3Ivq8aCJ7fbfkTX0fTx4mqojySfRk2MtcBcMxG3fjAHko5KDVqzBoIsjoIWlpRoEpdDxELixjY6+U00hLGG6MKHASM0SsLQqWRMFEMYVjRvuElaL6nB/TxFb6qVQC4RfTjq8l6Xk2YQ82l9/df+ENr95nFCS2On+nJuH1KGG3HDSdKPSPeCwuBqFun4VEh9TpWU802yyS1Gb9RqXIcpGkdBJWnUd2bwKXO7Axw7w+C10FIfJpH13qHZnxprrJ3oHxvWzF6ZBcGkZR7ViIQVacAFULOKvShw6o+UMtQu4WvJyYFVuTbJzHe9xqE1Ie/00htw5dk6hUsdr3T5RuQxrh9CQBprP4JI2ETdYDO5K3toYIwTm9t2oOmZCmV4gEwpkqqVVuSoC7y5UylnxRshvCQk9dvbbOad0uTXeuqiVYtt8bCkv2PyL2cajVyG8nnOIG/XLVgmaVZz1xkMfKDqQrpCt1sUfDK/E+9jGK40c0SLjqyilju17/deR1qN2hgktb3ZHakbHtXZ99IewJBNVLFi0zfb2T44YRK2pbemSkuurBfXuFDTN9ohkvr9cGzeGuumI=
  - secure: Za8Fg9LJHB8sov9kMiwBEroCEqHHu/rFspMTWUrG5u/ru23MN7ehdv8NNlbKmnmyLiORyQSbhEa0QKZ5SyJ00u66e/nw2L7xhUitFCZ5LPdb/ZPZ6+6HQuKIHoNgiGZjokSdYk7aK/PUsAJ2eqtLPdyhSkgyK9DV+FnOtisibdqrnQXBO7dD41YnMSElXB8Se9QPdmZjctIOoCj2L4HRicvvOMXDtK5ZrMMGhWJolHrhJJQkxPkaZwz6k1l29/ygrB2dNa1cZsA4Wgwvc3OHrt339FpTQ7cHq67VT2pBAIkN5uet0n534ttrEIwWs5eZaV9ZN2PnvlwRlG1UnStKY/oizjut2qhGwTb9/WxX427DFSFZ/afQDO0f5rQQ4ADUrdEwhxMy6N3u++hRf4Z3axeyNV95fQBfP0fi7PGoxeu/IpU+Hkh1YPfam/nXDiuNvs7LiYETA2eROU/s7dgOYPHSHvhcSxNDdVdwGB2GGoBJ9NzlHsTYVBjf/fXZMlNRdFT1BnFPdXCReQ+XHrKO3K0GQcC1pBHNJwo7K/Ez77lg6L8/uwj9pMh/w2G/FIbGQYg8YM7Y11oVtFobIDc4ve0SAW+SeEuIgYSltXuBomcNWCB84JWWHBxwOZ43n1O7qTVxrP9kYyV99XXdsVKoQTISBck6pq8/T0UtQFcrryA=
